<?php

/**
 * Implements hook_library_info_alter().
 */
function es6_tabledrag_library_info_alter(&$libraries, $extension) {
    if ($extension == 'core') {
        unset($libraries['drupal.tabledrag']['js']['misc/tabledrag.js']);

        $libraries['drupal.tabledrag']['js']['/libraries/tabledrag/js/TableDrag.js'] = [
            'attributes' => ['type' => 'module']
        ];

        $libraries['drupal.tabledrag']['css']['base']['http://localhost:9001/tabledrag.css'] = ['external' => TRUE];
        $libraries['drupal.tabledrag']['css']['base']['/' . drupal_get_path('module', 'es6_tabledrag') . '/css/tabledrag.css'] = [
            'external' => TRUE
        ];

        $libraries['drupal.tabledrag']['js']['/' . drupal_get_path('module', 'es6_tabledrag') . '/js/es6_tabledrag.js'] = [];
    }
}